### ISSUE TITLE
如何自定义样式

### ISSUE THREAD

**Issue by kidylee** [ai-chen2050/obsidian-wechat-public-platform#10]
很喜欢这个项目，真是我工作流中缺少的一环。

想了解一下如何自定义样式，我看到有一个 custom.css, 但是不了解机制，谢谢。

**Comment by kidylee** [comment]
我找打了自定义文件，并且复制样式： https://github.com/mdnice/markdown-nice/issues/43

但是好像没有起作用

**Comment by ai-chen2050** [comment]
> 很喜欢这个项目，真是我工作流中缺少的一环。
> 
> 想了解一下如何自定义样式，我看到有一个 custom.css, 但是不了解机制，谢谢。

很高兴能帮到你，如果喜欢就 GitHub 点下 star, 或者插件微信打赏点小红包。独立开发，用爱发电 ❤️，感谢支持。

**Comment by ai-chen2050** [comment]
> 我找到了自定义文件，并且复制样式： [mdnice/markdown-nice#43](https://github.com/mdnice/markdown-nice/issues/43)
> 
> 但是好像没有起作用

设置样式之后，需要重启插件，才可生效。谢谢 ❤️

```css
/* 自定义样式 - 自定义样式会覆盖默认样式
 * 默认样式请参考: https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/master/src/style/wechatFormat.ts
 * ”兰青“
*/

/*自定义样式，实时生效*/

/* 全局属性
 * 页边距 padding: 30px;
 * 全文字体 font-family: ptima-Regular;
 * 英文换行 word-break: break-all;
 */
#nice .layout {}

/* 段落，下方未标注标签参数均同此处
 * 上边距 margin-top: 5px;
 * 下边距 margin-bottom: 5px;
 * 行高 line-height: 26px;
 * 词间距 word-spacing: 3px;
 * 字间距 letter-spacing: 3px;
 * 对齐 text-align: left;
 * 颜色 color: #3e3e3e;
 * 字体大小 font-size: 16px;
 * 首行缩进 text-indent: 2em;
 */
#nice p {
  text-align: justify;
}

/* 一级标题 */
#nice h1 {
  font-size: 1.8em;
  color: #009688;
  margin: 1.2em auto;
  text-align: center;
  border-bottom: 1px solid #009688;
}

/* 一级标题内容 */
#nice h1 span {}

/* 一级标题修饰 请参考有实例的主题 */
#nice h1:after {}

/* 二级标题 */
#nice h2 {
  color: #009688;
  padding-left: 10px;
  margin: 1em auto;
  border-left: 3px solid #009688;
}

/* 二级标题内容 */
#nice h2 span {}

/* 二级标题修饰 请参考有实例的主题 */
#nice h2:after {}

/* 三级标题 */
#nice h3 {
  margin: 0.6em auto;
  padding-left: 10px;
  border-left: 2px solid #009688;
}

/* 三级标题内容 */
#nice h3 span {}

/* 三级标题修饰 请参考有实例的主题 */
#nice h3:after {}

/* 四级标题 */
#nice h4 {
  margin: 0.6em auto;
  font-size: 1.2em;
  padding-left: 10px;
  border-left: 2px dashed #009688;
}

/* 五级标题 */
#nice h5 {
  margin: 0.6em auto;
  font-size: 1.1em;
  padding-left: 10px;
  border-left: 1px dashed #009688;
}

/* 六级标题 */
#nice h6 {
  margin: 0.6em auto;
  font-size: 1em;
  padding-left: 10px;
  border-left: 1px dotted #009688;
}

/* 列表内容 */
#nice li {}

/* 引用
 * 左边缘颜色 border-left-color: black;
 * 背景色 background: gray;
 */
#nice blockquote {
  border-left: 2px solid #888;
  border-right: 2px solid #888;
  padding-left: 1em;
  color: #777;
}

/* 引用文字 */
#nice blockquote p {}

/* 链接 */
#nice a {
  color: #009688;
  border-bottom: 1px solid #009688;
}

/* 加粗 */
#nice strong {}

/* 斜体 */
#nice em {}

/* 加粗斜体 */
#nice strong em {}

/* 删除线 */
#nice del {}

/* 分隔线
 * 粗细、样式和颜色
 * border-top: 1px solid #3e3e3e;
 */
#nice hr {
  margin: 20px 0;
}

/* 图片
 * 宽度 width: 80%;
 * 居中 margin: 0 auto;
 * 居左 margin: 0 0;
 */
#nice img {}

/* 图片描述文字 */
#nice figcaption {}

/* 行内代码 */
#nice p code,
li code {
  color: #009688;
}

/* 非微信代码块
 * 代码块不换行 display: -webkit-box !important;
 * 代码块换行 display: block;
 */
#nice pre code {}

/*
 * 表格内的单元格
 * 字体大小 font-size: 16px;
 * 边框 border: 1px solid #ccc;
 * 内边距 padding: 5px 10px;
 */
#nice table tr th {
  border: 1px solid #009688;
  background-color: #009688;
  color: #f8f8f8;
  border-bottom: 0;
}

#nice table tr td {
  border: 1px solid #009688;
}

#nice table tr:nth-child(2n) {
  background-color: #f8f8f8;
}

/* 脚注文字 */
#nice .footnote-word {
  color: #009688;
}

/* 脚注上标 */
#nice .footnote-ref {
  color: #009688;
}

/* "参考资料"四个字 */
#nice .footnotes-sep {}

/* 参考资料编号 */
#nice .footnote-num {}

/* 参考资料文字 */
#nice .footnote-item p {}

/* 参考资料解释 */
#nice .footnote-item p em {}
```
